FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Test Async .Net Core Website/Test Async .Net Core Website.csproj", "Test Async .Net Core Website/"]

RUN dotnet restore "Test Async .Net Core Website/Test Async .Net Core Website.csproj"
COPY . .
WORKDIR "/src/Test Async .Net Core Website"
RUN dotnet build --no-restore "Test Async .Net Core Website.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]